#!/usr/bin/gawk -f

# Number of ways to color edges of a n-gon using c colors, allowing only rotations
# Wolfgang Lauffher 2024

function find_unique_colorings (edges,     c, e, r) {
        local colors
        local counted_within_this_rotation
        for (c=1; c<=COLORS; c++) {
                Color[edges]=c
                if (edges <= 1) {
                        counted_within_this_rotation=0
                        for (r=1; r<=EDGES; r++) { # Rotation
                                colors="#"
                                for (e=r; e<=EDGES+r-1; e++) {
                                        colors=colors " " Color[(e-1) % EDGES +1]
                                }
                                if (++Seen[colors]==1 && !counted_within_this_rotation++) COLORINGS++
                        }
                }
                else {
                        find_unique_colorings(edges-1)
                }
        }
}

BEGIN {
        EDGES=ARGV[1] ? ARGV[1] : 1
        COLORS=ARGV[2] ? ARGV[2] : 1

        find_unique_colorings(EDGES)

        print "Edges: " EDGES " Colors: " COLORS " Unique Colorings: " COLORINGS
}


